name: Smoke test

on:
  push:
  workflow_dispatch:

jobs:
  run-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Smoke run (help or no-op)
        run: |
          set -e
          if [ -f "run_experiment.py" ]; then
            python run_experiment.py -h || true
          fi
          echo "SMOKE OK: ambiente creato e script avviabile"
